# Generated by Django 4.0.6 on 2022-08-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_transaction_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='amount',
            new_name='number',
        ),
    ]
